apiVersion: v1
kind: Namespace
metadata:
  name: wireguard
  labels:
    name: wireguard
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: wireguard
  namespace: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      nodeSelector:
        ipAddress: 192.168.68.55 # locking this to one particular node because of port forwarding rule at the router
      containers:
        - name: wireguard
          image: weejewel/wg-easy
          env:
            - name: WG_HOST
              value: "grantstannard.com"
            - name: WG_DEFAULT_DNS
              value: "192.168.68.203"
            - name: WG_MTU
              value: "1000"
            - name: WG_ALLOWED_IPS
              value: "0.0.0.0/0, ::/0"
          securityContext:	# I am not sure if following is required, I haven't tried it without
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
          volumeMounts:
            - name: config	# stores wg-easy configuration
              mountPath: /etc/wireguard
      volumes:
        - name: config
          nfs:
            server: 192.168.68.58
            path: /mnt/fast_speed/opt/kubernetes/wireguard
---
apiVersion: v1
kind: Service
metadata:
  name: wireguard
  namespace: wireguard
  labels:
    app: wireguard
spec:
  type: LoadBalancer
  ports:
    - name: wireguard
      targetPort: 51820
      port: 51820
      protocol: UDP
    - name: web
      targetPort: 51821
      port: 51821
  selector:
    app: wireguard
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wireguard
  namespace: wireguard
spec:
  rules:
    - host: wireguard.grantstannard.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wireguard
                port:
                  number: 51821