---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/GrantStannard/homelab.git
      targetRevision: main
      ref: homelab
    - repoURL: https://traefik.github.io/charts
      targetRevision:  23.0.1
      chart: traefik
      helm:
        valueFiles:
          - $homelab/traefik/alpha/values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik
